config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api do
    resources :monkeys
    resources :users, only: [:index, :show, :create]
    resources :sessions, only: [:create, :destroy]
    resources :properties
  end

  resources :monkeys

end

app/models/monkey.rb
class Monkey < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base

  validates :address, :user_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 },
                  presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  before_create :generate_authentication_token!

  validates :auth_token, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :properties, dependent: :destroy

   def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end

app/controllers/api/monkeys_controller.rb
class Api::MonkeysController <  ApplicationController
  skip_before_filter :verify_authenticity_token
  def index
    render json: Monkey.all
  end

  def show
    monkey = Monkey.find(params[:id])
    render json: monkey
  end

  def create
    monkey = Monkey.new(monkey_params)
    if monkey.save
      render json: {
        status: 200,
        message: "Successfully created a monkey",
        monkey: monkey
      }.to_json
    else
      render status: 500, json: {
        errors: monkey.errors
      }.to_json
    end
  end

  def update
    monkey = Monkey.find(params[:id])
    if monkey.update(monkey_params)
      render json: {
        status: 200,
        message: "Successfully updated a monkey",
        monkey: monkey
      }.to_json
    end
  end

  def destroy
    monkey = Monkey.find(params[:id])
    monkey.destroy
    render json:{
      status: 200,
      message: 'Successfully deleted monkey'
    }.to_json
  end

  private

  def monkey_params
    params.require('monkey').permit('name')
  end

end

app/controllers/api/properties_controller.rb
class Api::PropertiesController <  ApplicationController
  skip_before_filter :verify_authenticity_token


  def index
    render json: Property.all.where(user_id: current_user.id)
  end

  def show
    property = Property.find(params[:id])
    render json: property
  end

  def create
    new_params = property_params
    new_params[:user_id] = current_user.id
    property = Property.new(new_params)
    if property.save
      render json: {
        status: 200,
        message: "Successfully created a property",
        property: property
      }.to_json
    else
      render status: 500, json: {
        errors: property.errors
      }.to_json
    end
  end

  def update
    property = Property.find(params[:id])
    if property.update(property_params)
      render json: {
        status: 200,
        message: "Successfully updated a property",
        property: property
      }.to_json
    end
  end

  def destroy
    # check the users token here
    property = Property.find(params[:id])
    property.destroy
    render json:{
      status: 200,
      message: 'Successfully deleted property'
    }.to_json
  end

  private

  def property_params
    @property_params ||= params.require('property').permit(['address', 'price','user_id'])
  end

end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ApplicationController

  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user, store: false
      user.generate_authentication_token!
      user.save
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: "Invalid email or password" }, status: 422
    end
  end

  # def destroy
  #   user = User.find_by(auth_token: params[:id])
  #   user.generate_authentication_token!
  #   user.save
  #   head 204
  # end


  def destroy
    byebug
    #current_user.destroy
    #head 204
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authenticate_with_token!, only: [:index, :update, :destroy]
  respond_to :json

  def index
    render json: User.all
  end


  def show
    u = User.find(params[:id])
    render json: u
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user, status: 201, location: [:api, user]
    else
      render json: { errors: user.errors }, status: 422
    end
  end

  def update
    user = current_user

    if user.update(user_params)
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: user.errors }, status: 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include Authenticable

end

app/controllers/concerns/authenticable.rb
module Authenticable

  # Devise methods overwrites
  def current_user
    @current_user ||= User.find_by(auth_token: request.headers['Authorization'])
  end

  def authenticate_with_token!
    render json: { errors: "Not authenticated" },
                status: :unauthorized unless current_user.present?
  end
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  before_action :set_monkey, only: [:show, :edit, :update, :destroy]

  # GET /monkeys
  # GET /monkeys.json
  def index
    @monkeys = Monkey.all
  end

  # GET /monkeys/1
  # GET /monkeys/1.json
  def show
  end

  # GET /monkeys/new
  def new
    @monkey = Monkey.new
  end

  # GET /monkeys/1/edit
  def edit
  end

  # POST /monkeys
  # POST /monkeys.json
  def create
    @monkey = Monkey.new(monkey_params)

    respond_to do |format|
      if @monkey.save
        format.html { redirect_to @monkey, notice: 'Monkey was successfully created.' }
        format.json { render :show, status: :created, location: @monkey }
      else
        format.html { render :new }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monkeys/1
  # PATCH/PUT /monkeys/1.json
  def update
    respond_to do |format|
      if @monkey.update(monkey_params)
        format.html { redirect_to @monkey, notice: 'Monkey was successfully updated.' }
        format.json { render :show, status: :ok, location: @monkey }
      else
        format.html { render :edit }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monkeys/1
  # DELETE /monkeys/1.json
  def destroy
    @monkey.destroy
    respond_to do |format|
      format.html { redirect_to monkeys_url, notice: 'Monkey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monkey
      @monkey = Monkey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monkey_params
      params.require(:monkey).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonkeyingAround</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/monkeys/_form.html.erb
<%= form_for(@monkey) do |f| %>
  <% if @monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% @monkey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing Monkey</h1>

<%= render 'form' %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monkeys</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monkeys.each do |monkey| %>
      <tr>
        <td><%= monkey.id %></td>
        <td><%= monkey.name %></td>
        <td><%= monkey.age %></td>
        <td><%= link_to 'Show', monkey %></td>
        <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
        <td><%= link_to 'Destroy', monkey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New Monkey</h1>

<%= render 'form' %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monkey.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @monkey.age %>
</p>

<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>